
/* A program to display a simple Knightrider animation*/ 
/* YOUTUBE LINK: https://youtu.be/fp7iCY99yjg*/


int LED1 = 1;
int LED2 = 3;
int LED3 = 5;
int LED4 = 7;
int LED5 = 9;
int LED6 = 2;
int LED7 = 4;
int LED8 = 6;
int LED9 = 8;
int LED10 = 10;
int LED11 = A1;
int LED12 = A2;
int LED13 = A3;
int LED14 = A4;
int LED15 = A5;
int LED16 = 11;
int LED17 = 12;
int LED18 = 13;


void setup() {
   pinMode(LED1, OUTPUT);
   pinMode(LED2, OUTPUT);
   pinMode(LED3, OUTPUT);
   pinMode(LED4, OUTPUT);
   pinMode(LED5, OUTPUT);
   pinMode(LED6, OUTPUT);
   pinMode(LED7, OUTPUT);
   pinMode(LED8, OUTPUT);
   pinMode(LED9, OUTPUT);
   pinMode(LED10, OUTPUT);
   pinMode(LED11, OUTPUT);   
   pinMode(LED12, OUTPUT);
   pinMode(LED13, OUTPUT);
   pinMode(LED14, OUTPUT);
   pinMode(LED15, OUTPUT);
   pinMode(LED16, OUTPUT);
   pinMode(LED17, OUTPUT);
   pinMode(LED18, OUTPUT);
}

void loop() {

  //SEQUENCE 1
    digitalWrite(LED1, HIGH);     
    delay(50);
    digitalWrite(LED1, LOW);     
    delay(50);
    digitalWrite(LED2, HIGH);
    delay(50);
    digitalWrite(LED2, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);
    delay(50);
    digitalWrite(LED3, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);
    delay(50);
    digitalWrite(LED4, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);
    delay(50);
    digitalWrite(LED5, LOW);
    delay(50);

    digitalWrite(LED6, HIGH);     
    delay(50);
    digitalWrite(LED6, LOW); 
    delay(50);
    digitalWrite(LED7, HIGH);
    delay(50);
    digitalWrite(LED7, LOW);
    delay(50);
    digitalWrite(LED8, HIGH);
    delay(50);
    digitalWrite(LED8, LOW);
    delay(50);
    digitalWrite(LED9, HIGH);
    delay(50);
    digitalWrite(LED9, LOW);
    delay(50);
    digitalWrite(LED10, HIGH);
    delay(50);
    digitalWrite(LED10, LOW);
    delay(50);

    digitalWrite(LED11, HIGH);     
    delay(50);
    digitalWrite(LED11, LOW);     
    delay(50);
    digitalWrite(LED12, HIGH);
    delay(50);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED13, HIGH);
    delay(50);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED14, HIGH);
    delay(50);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED15, HIGH);    
    delay(50);
    digitalWrite(LED15, LOW);
    delay(100);

  //SEQUENCE 2 columns 
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(300);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(300);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(300);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(300);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(300);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(300);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(300);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(300);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(300);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(300);


    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(200);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(200);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(200);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(200);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(200);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(200);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(200);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(200);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(200);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(200);


    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(100);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(100);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(100);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(100);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(100);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(100);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(100);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(100);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(100);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(100);

    
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
 
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
 
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
 
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);

    
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);

    
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);
        
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);
        
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);        
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);
        
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);        
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);
        
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);


//REVERSE //   
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
//REVERSE END//
    
    // normal //
    
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);

    // reverse //

    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(10);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(10);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(10);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(10);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(10);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(10);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(10);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(10);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(10);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(10);
   
    // normal //
    
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);

    // reverse //

    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    // normal //
    
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);

    // reverse //

    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    // normal //
    
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);

    // reverse //

    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);

 // THROUGH //
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);

    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);

    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);

    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);

    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);

    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);

 // WAVE //
        // normal //
    
        digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
        digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
        digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
        digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
        digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);

    //BACK AND FORTH
        digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);

    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);   
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50); 
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);

    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);   
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50); 
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);

    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);   
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50); 
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);

    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);   
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50); 
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50); 
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);

    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50);    
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED4, LOW);
    digitalWrite(LED9, LOW);
    digitalWrite(LED14, LOW);
    delay(50);   
    digitalWrite(LED3, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED2, LOW);
    digitalWrite(LED7, LOW);
    digitalWrite(LED12, LOW);
    delay(50); 
    digitalWrite(LED1, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED11, LOW);
    delay(50);

    

  //FINAL SEQUENCE
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED2, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED4, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED7, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED9, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
  
    digitalWrite(LED1, HIGH);     
    delay(50);
    digitalWrite(LED1, LOW);     
    delay(50);
    digitalWrite(LED2, HIGH);
    delay(50);
    digitalWrite(LED2, LOW);
    delay(50);
    digitalWrite(LED11, HIGH);
    delay(50);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);
    delay(50);
    digitalWrite(LED3, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);
    delay(50);
    digitalWrite(LED4, LOW);
    delay(50);

    digitalWrite(LED12, HIGH);     
    delay(50);
    digitalWrite(LED12, LOW); 
    delay(50);
    digitalWrite(LED5, HIGH);
    delay(50);
    digitalWrite(LED5, LOW);
    delay(50);
    digitalWrite(LED6, HIGH);
    delay(50);
    digitalWrite(LED6, LOW);
    delay(50);
    digitalWrite(LED13, HIGH);
    delay(50);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED7, HIGH);
    delay(50);
    digitalWrite(LED7, LOW);
    delay(50);

    digitalWrite(LED8, HIGH);     
    delay(50);
    digitalWrite(LED8, LOW);     
    delay(50);
    digitalWrite(LED14, HIGH);
    delay(50);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED9, HIGH);
    delay(50);
    digitalWrite(LED9, LOW);
    delay(50);
    digitalWrite(LED10, HIGH);
    delay(50);
    digitalWrite(LED10, LOW);
    delay(50);
    digitalWrite(LED15, HIGH);    
    delay(50);
    digitalWrite(LED15, LOW);

    digitalWrite(LED1, HIGH);   
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED2, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED4, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED7, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED9, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
    digitalWrite(LED1, HIGH);   
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED2, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED4, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED7, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED9, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);
  
    digitalWrite(LED1, HIGH);     
    delay(50);
    digitalWrite(LED1, LOW);     
    delay(50);
    digitalWrite(LED2, HIGH);
    delay(50);
    digitalWrite(LED2, LOW);
    delay(50);
    digitalWrite(LED11, HIGH);
    delay(50);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);
    delay(50);
    digitalWrite(LED3, LOW);
    delay(50);
    digitalWrite(LED4, HIGH);
    delay(50);
    digitalWrite(LED4, LOW);
    delay(50);

    digitalWrite(LED12, HIGH);     
    delay(50);
    digitalWrite(LED12, LOW); 
    delay(50);
    digitalWrite(LED5, HIGH);
    delay(50);
    digitalWrite(LED5, LOW);
    delay(50);
    digitalWrite(LED6, HIGH);
    delay(50);
    digitalWrite(LED6, LOW);
    delay(50);
    digitalWrite(LED13, HIGH);
    delay(50);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED7, HIGH);
    delay(50);
    digitalWrite(LED7, LOW);
    delay(50);

    digitalWrite(LED8, HIGH);     
    delay(50);
    digitalWrite(LED8, LOW);     
    delay(50);
    digitalWrite(LED14, HIGH);
    delay(50);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED9, HIGH);
    delay(50);
    digitalWrite(LED9, LOW);
    delay(50);
    digitalWrite(LED10, HIGH);
    delay(50);
    digitalWrite(LED10, LOW);
    delay(50);
    digitalWrite(LED15, HIGH);    
    delay(50);
    digitalWrite(LED15, LOW);

    digitalWrite(LED1, HIGH);   
    digitalWrite(LED2, HIGH);   
    digitalWrite(LED11, HIGH);   
    delay(50);
    digitalWrite(LED1, LOW);
    digitalWrite(LED2, LOW);
    digitalWrite(LED11, LOW);
    delay(50);
    digitalWrite(LED3, HIGH);   
    digitalWrite(LED4, HIGH);   
    digitalWrite(LED12, HIGH);   
    delay(50);
    digitalWrite(LED3, LOW);
    digitalWrite(LED4, LOW);
    digitalWrite(LED12, LOW);
    delay(50);
    digitalWrite(LED5, HIGH);   
    digitalWrite(LED6, HIGH);   
    digitalWrite(LED13, HIGH);   
    delay(50);
    digitalWrite(LED5, LOW);
    digitalWrite(LED6, LOW);
    digitalWrite(LED13, LOW);
    delay(50);
    digitalWrite(LED7, HIGH);   
    digitalWrite(LED8, HIGH);   
    digitalWrite(LED14, HIGH);   
    delay(50);
    digitalWrite(LED7, LOW);
    digitalWrite(LED8, LOW);
    digitalWrite(LED14, LOW);
    delay(50);
    digitalWrite(LED9, HIGH);   
    digitalWrite(LED10, HIGH);   
    digitalWrite(LED15, HIGH);   
    delay(50);
    digitalWrite(LED9, LOW);
    digitalWrite(LED10, LOW);
    digitalWrite(LED15, LOW);
    delay(50);

    //GREEN
    digitalWrite(LED16, HIGH);  
    delay(200); 
    digitalWrite(LED17, HIGH);   
    delay(200);
    digitalWrite(LED18, HIGH); 
    delay(200);
    digitalWrite(LED16, LOW); 
    digitalWrite(LED17, LOW); 
    digitalWrite(LED18, LOW); 
    delay(500);
    digitalWrite(LED16, HIGH); 
    digitalWrite(LED17, HIGH); 
    digitalWrite(LED18, HIGH);
    delay(50);
    digitalWrite(LED16, LOW); 
    digitalWrite(LED17, LOW); 
    digitalWrite(LED18, LOW);
    delay(50);
    digitalWrite(LED16, HIGH); 
    digitalWrite(LED17, HIGH); 
    digitalWrite(LED18, HIGH);
    delay(50);
    digitalWrite(LED16, LOW); 
    digitalWrite(LED17, LOW); 
    digitalWrite(LED18, LOW);
    delay(200);
    digitalWrite(LED16, HIGH); 
    digitalWrite(LED17, HIGH); 
    digitalWrite(LED18, HIGH);
    delay(5000);

    digitalWrite(LED16, LOW);
    digitalWrite(LED17, LOW);
    digitalWrite(LED18, LOW);

    delay(2000);

        digitalWrite(LED16, LOW); 
    digitalWrite(LED17, LOW); 
    digitalWrite(LED18, LOW); 
    delay(500);
    digitalWrite(LED16, HIGH); 
    digitalWrite(LED17, HIGH); 
    digitalWrite(LED18, HIGH);
    delay(50);
    digitalWrite(LED16, LOW); 
    digitalWrite(LED17, LOW); 
    digitalWrite(LED18, LOW);
    delay(50);
    digitalWrite(LED16, HIGH); 
    digitalWrite(LED17, HIGH); 
    digitalWrite(LED18, HIGH);
    delay(50);
    digitalWrite(LED16, LOW); 
    digitalWrite(LED17, LOW); 
    digitalWrite(LED18, LOW);
    delay(200);
    digitalWrite(LED16, HIGH); 
    digitalWrite(LED17, HIGH); 
    digitalWrite(LED18, HIGH);
    
    delay(200);
}
